// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NRTA.Core.Data;

namespace NRTA.Core.Migrations
{
    [DbContext(typeof(NRTADbContext))]
    [Migration("20200906095439_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("NRTA.Core.Models.ExamQuestion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("A")
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer")
                        .HasColumnType("TEXT");

                    b.Property<string>("B")
                        .HasColumnType("TEXT");

                    b.Property<string>("C")
                        .HasColumnType("TEXT");

                    b.Property<string>("D")
                        .HasColumnType("TEXT");

                    b.Property<string>("E")
                        .HasColumnType("TEXT");

                    b.Property<string>("F")
                        .HasColumnType("TEXT");

                    b.Property<string>("G")
                        .HasColumnType("TEXT");

                    b.Property<string>("H")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
